services:
  - type: web
    name: auca-certificate-portal
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: UseMockData
        value: true
      - key: DBUS_SESSION_BUS_ADDRESS
        value: /dev/null
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
